/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  await knex('gamelog').del()
  await knex('gamelog').insert([
    {
      game: 'God of War Ragnarok',
      played_before: false,
      clocked_before: false,
      platform: 'PS5',
      start_date: 'unknown',
      finish_date: '31/12/2023',
      playtime_estimate: '25hrs',
      playtime_final: '23hr 25min',
      gameplay_rating: 7,
      story_rating: 9,
      graphics_rating: 10,
      performance_rating: 9,
      fun_rating: 7,
      final_rating: 4,
      final_thoughts:
        'The UI was a big downgrade, menus looked like they were straight out of Shadow of Mordor (not in a good way). Map was next to useless outside of fast travel. It looked amazing and the plot was next to perfect (with a few pacing problems here and there) but something felt lacking overall. Still an incredible game.',
    },
    {
      game: 'Final Fantasy VII Remake',
      played_before: true,
      clocked_before: false,
      platform: 'PS4',
      start_date: '01/01/2024',
      finish_date: '04/01/2024',
      playtime_estimate: '42.5 hrs',
      playtime_final: '23hrs 51min',
      gameplay_rating: 5,
      story_rating: 7,
      graphics_rating: 10,
      performance_rating: 7,
      fun_rating: 5,
      final_rating: 3,
      final_thoughts:
        'Without the nostalgia glasses I assume you are meant to put on while playing, this is a very mid game. After watching a few youtube videos this "remake" is giving NGE Rebuild vibes with the multiple timelines... curious to see how the second half plays out when it releases.',
    },
    {
      game: 'Spyro the Dragon (Reignited Triology)',
      played_before: true,
      clocked_before: true,
      platform: 'PS4',
      start_date: '04/01/2024',
      finish_date: '06/01/2024',
      playtime_estimate: '10hrs',
      playtime_final: '4hrs 24min',
      gameplay_rating: 6,
      story_rating: 7,
      graphics_rating: 10,
      performance_rating: 9,
      fun_rating: 8,
      final_rating: 3,
      final_thoughts: 'Classic.',
    },
    {
      game: 'Baldurs Gate 3',
      played_before: true,
      clocked_before: false,
      platform: 'PS5',
      start_date: '07/01/2024',
      finish_date: '20/01/2024',
      playtime_estimate: '60hrs',
      playtime_final: '41hrs 16min',
      gameplay_rating: 9,
      story_rating: 9,
      graphics_rating: 9,
      performance_rating: 7,
      fun_rating: 10,
      final_rating: 4,
      final_thoughts:
        'There is too much to even talk about here in the best way.',
    },
    {
      game: 'The Last of Us Part II Remastered',
      played_before: false,
      clocked_before: false,
      platform: 'PS5',
      start_date: '01/02/2024',
      finish_date: '06/02/2024',
      playtime_estimate: '27hrs',
      playtime_final: '22hrs 17min',
      gameplay_rating: 9,
      story_rating: 10,
      graphics_rating: 10,
      performance_rating: 9,
      fun_rating: 10,
      final_rating: 5,
      final_thoughts:
        'This game has been incredibly divisive among fans; I am most definitely on the side that loves this game. The tone, the atmosphere, the score, the performances... sure there were points where the game struggled to keep up with what I was doing (usually panicking in the heat of battle as one does). A beautiful tragedy about loss and grief. Possible contender for my favourite game experience of all time.',
    },
    {
      game: 'Guitar Hero III Legends of Rock',
      played_before: true,
      clocked_before: true,
      platform: 'PS2',
      start_date: '06/02/2024',
      finish_date: '06/02/2024',
      playtime_estimate: null,
      playtime_final: null,
      gameplay_rating: 8,
      story_rating: 7,
      graphics_rating: 8,
      performance_rating: 7,
      fun_rating: 9,
      final_rating: 4,
      final_thoughts:
        'This was more a nostalgia trip than anything else. Gameplay definitely improved across the first three GH titles. Fun plot. Good soundtrack with what sounded like the authentic recordings of songs and not just a cover band. Really wish I had a guitar to play this with.',
    },
    {
      game: 'Elden Ring',
      played_before: true,
      clocked_before: true,
      platform: 'XBOX Series S',
      start_date: null,
      finish_date: '10/02/2024',
      playtime_estimate: '58hrs',
      playtime_final: '54hrs 16min',
      gameplay_rating: 9,
      story_rating: 7,
      graphics_rating: 10,
      performance_rating: 9,
      fun_rating: 10,
      final_rating: 4,
      final_thoughts:
        'Last time I played (on a save I accidentally deleted during this run) I did a dexterity build, so this time I went strength. Classic Blaidd armour and berserk greatsword type shit. Breezed through most of it once I got the hang of the slower attack speed. Still thoroughly enjoyed this game a second time around. Might have to do magic build next. Love you Ranni.',
    },
    {
      game: 'Shipwrecked 64',
      played_before: false,
      clocked_before: false,
      platform: 'PC',
      start_date: '01/03/2024',
      finish_date: '05/03/2024',
      playtime_estimate: '10hrs',
      playtime_final: '11hrs 24min',
      gameplay_rating: 8,
      story_rating: 8,
      graphics_rating: 8,
      performance_rating: 10,
      fun_rating: 9,
      final_rating: 4,
      final_thoughts:
        'This was the most fun and immersive gaming experience I may have ever had. The retro graphics, dynamic soundtrack and dizzying level layouts create a hypnotising ARG that you get to play first hand. There are lots of cheap jump scares. LOTS. Some are earned but it can get exhausting after a while. I turned my volume down for a lot of the latter half of this game where they get veeeery repetitive. I am gonna have to sit on the narrative for a bit, because I do and do not understand a lot of it currently. Playing this game solo is virtually impossible, so I must thank the several forums I used to get through this game. I never would have made it otherwise. Rest easy, Connor.',
    },
    {
      game: 'Helldivers 2',
      played_before: false,
      clocked_before: false,
      platform: 'PS5',
      start_date: null,
      finish_date: null,
      playtime_estimate: null,
      playtime_final: null,
      gameplay_rating: 9,
      story_rating: 8,
      graphics_rating: 10,
      performance_rating: 9,
      fun_rating: 10,
      final_rating: 5,
      final_thoughts: null,
    },
    {
      game: 'KinitoPET',
      played_before: false,
      clocked_before: false,
      platform: 'PC',
      start_date: '18/04/2024',
      finish_date: '19/04/2024',
      playtime_estimate: null,
      playtime_final: '3hrs 40min',
      gameplay_rating: 9,
      story_rating: 6,
      graphics_rating: 10,
      performance_rating: 7,
      fun_rating: 10,
      final_rating: 4,
      final_thoughts:
        'Fun, inventive and unique. Story leaves a fair bit to be desired as there just is not quite enough background to anything or anyone. A few single-page documents did not quite do it.  There were times I did feel genuine fear, and there were times I thought it could have been a lot better. Luckily the gameplay and fourth-wall breaks largely make up for any missteps this game makes.',
    },
    {
      game: 'A Little to the Left',
      played_before: false,
      clocked_before: false,
      platform: 'PC',
      start_date: null,
      finish_date: '17/04/2024',
      playtime_estimate: '3hrs',
      playtime_final: '4hr 20min',
      gameplay_rating: 9,
      story_rating: 7,
      graphics_rating: 7,
      performance_rating: 9,
      fun_rating: 8,
      final_rating: 4,
      final_thoughts: null,
    },
    {
      game: 'Elden Ring + Shadow of the Erdtree (DLC)',
      played_before: false,
      clocked_before: false,
      platform: 'PS5',
      start_date: null,
      finish_date: '29/06/2024',
      playtime_estimate: '80hrs',
      playtime_final: '116hrs 54min',
      gameplay_rating: 10,
      story_rating: 10,
      graphics_rating: 10,
      performance_rating: 9,
      fun_rating: 10,
      final_rating: 5,
      final_thoughts:
        'I thought the base game was a beast, but the DLC just ramped everything up. The narrative twists, the challenging but (mostly) fair gameplay, the world design... phenomenal craft. Is it perfect? Absolutely not. Is it game of the year again? Maybe. Has it posibbly taken the spot of my favourite game of all time? Almost definitely - that is, unless an Elden Ring 2 comes out.',
    },
    {
      game: 'Unpacking',
      played_before: false,
      clocked_before: false,
      platform: 'PS5',
      start_date: '20/08/2024',
      finish_date: '21/08/2024',
      playtime_estimate: '4hrs',
      playtime_final: '~6hrs',
      gameplay_rating: 8,
      story_rating: 8,
      graphics_rating: 8,
      performance_rating: 10,
      fun_rating: 10,
      final_rating: 4,
      final_thoughts:
        'Very fun, very cosy. Surprising amount of story can be told without dialogue. My only gripe with the game is how short it is, with the developers even saying there will not be DLC or anything of the sort. I played it via game pass, so not a loss for me at least, financially speaking.',
    },
    {
      game: 'Doom (2016)',
      played_before: true,
      clocked_before: true,
      platform: 'PS4',
      start_date: '23/08/2024',
      finish_date: '12/09/2024',
      playtime_estimate: '11hrs',
      playtime_final: '~13hrs',
      gameplay_rating: 8,
      story_rating: 6,
      graphics_rating: 8,
      performance_rating: 8,
      fun_rating: 9,
      final_rating: 4,
      final_thoughts:
        'This time around I feel like I knew how to look out for secrets and stuff like that, so by the time I made it to the latter half of the game I had managed to become pretty OP. It was nice being so powerful, but it did mean the ending of the game felt rather anticlimactic. No second phase for a final boss, when they had had multiple phases for earlier bosses, or even multiple bosses... felt a bit weird. Not bad overall, I am similarly looking forward to seeing how Doom Eternal has aged too.',
    },
    {
      game: 'Batman: Return to Arkham - Arkham Asylum',
      played_before: true,
      clocked_before: true,
      platform: 'PS4',
      start_date: '14/09/2024',
      finish_date: '15/09/2024',
      playtime_estimate: '11hrs',
      playtime_final: '~10hrs',
      gameplay_rating: 8,
      story_rating: 9,
      graphics_rating: 8,
      performance_rating: 7,
      fun_rating: 9,
      final_rating: 4,
      final_thoughts:
        'I do not remember it being as buggy as it was, so that was interesting. Still a really solid game all these years later. The features and gameplay I was longing for is in the sequels, so makes their absence here a little less saddening. Also wow it is really short!',
    },
    {
      game: 'Warhammer 40000: Space Marine II',
      played_before: false,
      clocked_before: false,
      platform: 'PS5',
      start_date: '18/09/2024',
      finish_date: '21/09/2024',
      playtime_estimate: '12hrs',
      playtime_final: '~9hrs',
      gameplay_rating: 9,
      story_rating: 7,
      graphics_rating: 10,
      performance_rating: 8,
      fun_rating: 9,
      final_rating: 4,
      final_thoughts:
        'This had some of the most insane skyboxes I have seen outside of a fromsoft game. Whatever tech they used for the hordes was incredible, and it made you feel even more like a badass as you slice and smash your way through them. The gameplay can get a little stale at points, and I think I pressed melee more than any other button. Anticlimactic ending too - I cannot stand when you have a final boss battle but they kill the boss in a cutscene. I think I understood the plot but... hard to say.',
    },
  ])
}
